### ISSUE TITLE
Netbeans Dev/Nightly

### ISSUE THREAD

**Issue by dynasource** [dzsessona/QuickOpener-NetBeans#54] opened 2015-07-15 09:28 UTC
Quickopener is the module I am using the most, unfortunately it is not supported anymore by the latest dev. release. I would like to say that I love to see this project to be continued.

**Comment by Joypeg** [comment] 2015-07-15 09:30
@dynasource thank you for the head up, i will fix it this week and release a new version.

**Comment by dynasource** [comment] 2015-07-15 09:58
great. Thanx!

**Comment by dynasource** [comment] 2015-07-30 10:08
any luck yet?

**Comment by dzsessona** [comment] 2015-09-01 20:34
doing it now

**Comment by dzsessona** [comment] 2015-09-01 21:31
in progress, please see https://netbeans.org/bugzilla/show_bug.cgi?id=254506

**Comment by markiewb** [comment] 2016-01-21 23:17
Duplicate of #56

**Closed by markiewb** 2016-01-21 23:17 UTC
